### ISSUE TITLE
Document `ObjectType`

### ISSUE THREAD

**Issue by Lucretiel** [plasticity-studios/tabletop-playground-api#1]
Currently, the[ `ObjectType`](https://api.tabletop-playground.com/enums/_api_.objecttype.html) enum variations aren't described in any public source of documentation. It's implied in [these patch notes](https://store.steampowered.com/news/app/838410/view/2530409200130933206) that `Penetrable` means that the object has collisions disabled:

> Make objects briefly penetrable when they are rotated on the table (using Q or E), so they don't collide with other objects on top

But otherwise there's no description of the behavior differences between these object types.

**Comment by plasticity-studios** [comment]
There's a small tooltip in the object properties window where players can change the type. ed8fe7c adds a description to the API docs.

**Comment by Lucretiel** [comment]
Oh that's perfect! Thanks so much for the fast turnaround
